using System;
using System.Collections.Generic;

namespace Domain.Entities
{
    public class AiGeneratedQuiz
    {
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public CourseModule? Module { get; set; }

        public int GeneratedByUserId { get; set; }
        public User? GeneratedByUser { get; set; }

        public int? GeneratedForEnrollmentId { get; set; }
        public Enrollment? GeneratedForEnrollment { get; set; }

        public string Output { get; set; } = string.Empty;
        public int Difficulty { get; set; } = 1;
        public int QuestionsCount { get; set; } = 5;
        public string Language { get; set; } = "en";
        public bool IncludeExplanations { get; set; } = true;

        // Student = generated by student for own study, Instructor = generated by instructor for assignment.
        public string GenerationSource { get; set; } = "Student";
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public bool IsActive { get; set; } = true;

        public ICollection<QuizAssignment> Assignments { get; set; } = new List<QuizAssignment>();
        public ICollection<StudentQuizAttempt> Attempts { get; set; } = new List<StudentQuizAttempt>();
    }
}
